package view;

import java.awt.Button;
import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.PopupMenu;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import view.JPanelSto;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Nikola
 */
public class JFrameGlavnaForma extends javax.swing.JFrame {

    private String konobar;

    /**
     * Creates new form JFrameGlavnaForma
     */
    public JFrameGlavnaForma(String korisnik) {
        initComponents();
        konobar = korisnik;
        pripremiFormu();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sto6 = new javax.swing.JButton();
        sto9 = new javax.swing.JButton();
        sto7 = new javax.swing.JButton();
        sto8 = new javax.swing.JButton();
        sto10 = new javax.swing.JButton();
        sto3 = new javax.swing.JButton();
        sto4 = new javax.swing.JButton();
        sto5 = new javax.swing.JButton();
        sto1 = new javax.swing.JButton();
        sto2 = new javax.swing.JButton();
        jButtonKrajRada = new javax.swing.JButton();
        jLabelKonobar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        sto6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/6.png"))); // NOI18N
        sto6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sto6ActionPerformed(evt);
            }
        });
        jPanel1.add(sto6);
        sto6.setBounds(80, 260, 70, 40);

        sto9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/9.png"))); // NOI18N
        sto9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sto9ActionPerformed(evt);
            }
        });
        jPanel1.add(sto9);
        sto9.setBounds(190, 160, 100, 50);

        sto7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/7.png"))); // NOI18N
        sto7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sto7ActionPerformed(evt);
            }
        });
        jPanel1.add(sto7);
        sto7.setBounds(20, 160, 100, 50);

        sto8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/8.png"))); // NOI18N
        sto8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sto8ActionPerformed(evt);
            }
        });
        jPanel1.add(sto8);
        sto8.setBounds(20, 40, 100, 50);

        sto10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/10.png"))); // NOI18N
        sto10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sto10ActionPerformed(evt);
            }
        });
        jPanel1.add(sto10);
        sto10.setBounds(520, 150, 80, 70);

        sto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/3.png"))); // NOI18N
        sto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sto3ActionPerformed(evt);
            }
        });
        jPanel1.add(sto3);
        sto3.setBounds(520, 350, 80, 100);

        sto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/4.png"))); // NOI18N
        sto4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sto4ActionPerformed(evt);
            }
        });
        jPanel1.add(sto4);
        sto4.setBounds(290, 380, 80, 70);

        sto5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/5.png"))); // NOI18N
        sto5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sto5ActionPerformed(evt);
            }
        });
        jPanel1.add(sto5);
        sto5.setBounds(70, 380, 80, 70);

        sto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/1.png"))); // NOI18N
        sto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sto1ActionPerformed(evt);
            }
        });
        jPanel1.add(sto1);
        sto1.setBounds(750, 250, 73, 70);

        sto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/2.png"))); // NOI18N
        sto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sto2ActionPerformed(evt);
            }
        });
        jPanel1.add(sto2);
        sto2.setBounds(750, 380, 80, 70);

        jButtonKrajRada.setBackground(new java.awt.Color(204, 255, 204));
        jButtonKrajRada.setText("Kraj rada");
        jButtonKrajRada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKrajRadaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonKrajRada);
        jButtonKrajRada.setBounds(50, 460, 100, 23);

        jLabelKonobar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelKonobar.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(jLabelKonobar);
        jLabelKonobar.setBounds(770, 60, 100, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nikola\\Desktop\\plan2.jpg")); // NOI18N
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 890, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 891, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sto7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sto7ActionPerformed
        JDialog dijalog = new JDialog(this, "Sto 7");
        JPanelSto jps = new JPanelSto(7);
        dijalog.add(jps);
        dijalog.pack();
        dijalog.setVisible(true);
    }//GEN-LAST:event_sto7ActionPerformed

    private void sto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sto1ActionPerformed
        JDialog dijalog = new JDialog(this, "Sto 1");
        JPanelSto jps = new JPanelSto(1);
        dijalog.add(jps);
        dijalog.pack();
        dijalog.setVisible(true);
    }//GEN-LAST:event_sto1ActionPerformed

    private void sto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sto2ActionPerformed
        JDialog dijalog = new JDialog(this, "Sto 2");
        JPanelSto jps = new JPanelSto(2);
        dijalog.add(jps);
        dijalog.pack();
        dijalog.setVisible(true);    }//GEN-LAST:event_sto2ActionPerformed

    private void sto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sto3ActionPerformed
        JDialog dijalog = new JDialog(this, "Sto 3");
        JPanelSto jps = new JPanelSto(3);
        dijalog.add(jps);
        dijalog.pack();
        dijalog.setVisible(true);    }//GEN-LAST:event_sto3ActionPerformed

    private void sto10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sto10ActionPerformed
        
        JDialog dijalog = new JDialog(this, "Sto 10");
        JPanelSto jps = new JPanelSto(10);
        dijalog.add(jps);
        dijalog.pack();
        dijalog.setVisible(true);
    }//GEN-LAST:event_sto10ActionPerformed

    private void sto4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sto4ActionPerformed
        JDialog dijalog = new JDialog(this, "Sto 4");
        JPanelSto jps = new JPanelSto(4);
        dijalog.add(jps);
        dijalog.pack();
        dijalog.setVisible(true);    }//GEN-LAST:event_sto4ActionPerformed

    private void sto9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sto9ActionPerformed
        JDialog dijalog = new JDialog(this, "Sto 9");
        JPanelSto jps = new JPanelSto(9);
        dijalog.add(jps);
        dijalog.pack();
        dijalog.setVisible(true);
    }//GEN-LAST:event_sto9ActionPerformed

    private void sto5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sto5ActionPerformed
        JDialog dijalog = new JDialog(this, "Sto 5");
        JPanelSto jps = new JPanelSto(5);
        dijalog.add(jps);
        dijalog.pack();
        dijalog.setVisible(true);    }//GEN-LAST:event_sto5ActionPerformed

    private void sto6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sto6ActionPerformed
        JDialog dijalog = new JDialog(this, "Sto 6");
        JPanelSto jps = new JPanelSto(6);
        dijalog.add(jps);
        dijalog.pack();
        dijalog.setVisible(true);    }//GEN-LAST:event_sto6ActionPerformed

    private void sto8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sto8ActionPerformed
        JDialog dijalog = new JDialog(this, "Sto 8");
        JPanelSto jps = new JPanelSto(8);
        dijalog.add(jps);
        dijalog.pack();
        dijalog.setVisible(true);
    }//GEN-LAST:event_sto8ActionPerformed

    private void jButtonKrajRadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKrajRadaActionPerformed
        System.exit(0);    }//GEN-LAST:event_jButtonKrajRadaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonKrajRada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelKonobar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton sto1;
    private javax.swing.JButton sto10;
    private javax.swing.JButton sto2;
    private javax.swing.JButton sto3;
    private javax.swing.JButton sto4;
    private javax.swing.JButton sto5;
    private javax.swing.JButton sto6;
    private javax.swing.JButton sto7;
    private javax.swing.JButton sto8;
    private javax.swing.JButton sto9;
    // End of variables declaration//GEN-END:variables

    private void pripremiFormu() {
        jLabelKonobar.setText("<html>Konobar:<br>" + konobar+"</html>");
    }
}
