/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.print.*;
import domen.Narudzbina;
import domen.Pice;
import domen.Sto;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import logic.Kontroler;
import view.model.TableModelSto;

/**
 *
 * @author Nikola
 */
public class JPanelSto extends javax.swing.JPanel {

    int stoid;

    /**
     * Creates new form JPanelSto
     */
    public JPanelSto(int brStola) {
        initComponents();
        pripremiFormu(brStola);
        stoid = brStola;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonDodaj = new javax.swing.JButton();
        jButtonKraj = new javax.swing.JButton();
        jButtonStampaj = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jComboBoxPica = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableNarudzbine = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jButtonDodaj.setText("Dodaj pice");
        jButtonDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajActionPerformed(evt);
            }
        });

        jButtonKraj.setText("Kraj unosa");
        jButtonKraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKrajActionPerformed(evt);
            }
        });

        jButtonStampaj.setText("Stampaj racun");
        jButtonStampaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStampajActionPerformed(evt);
            }
        });

        jComboBoxPica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTableNarudzbine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableNarudzbine);

        jLabel1.setText("kol:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonDodaj)
                            .addComponent(jComboBoxPica, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonKraj)
                                .addGap(44, 44, 44)
                                .addComponent(jButtonStampaj))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(29, 29, 29)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDodaj)
                    .addComponent(jButtonKraj)
                    .addComponent(jButtonStampaj))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonKrajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKrajActionPerformed
        TableModelSto tm = (TableModelSto) jTableNarudzbine.getModel();
        try {
            Kontroler.getInstance().sacuvajUpdateUBazi(tm.getLista());
        } catch (Exception ex) {
            Logger.getLogger(JPanelSto.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.getTopLevelAncestor().setVisible(false);    }//GEN-LAST:event_jButtonKrajActionPerformed

    private void jButtonDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajActionPerformed
        TableModelSto tm = (TableModelSto) jTableNarudzbine.getModel();

        Pice p = (Pice) jComboBoxPica.getSelectedItem();
        int kolicina = Integer.parseInt(jTextField1.getText());
        tm.dodajRed(stoid, p, kolicina);

    }//GEN-LAST:event_jButtonDodajActionPerformed

    private void jButtonStampajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStampajActionPerformed
        TableModelSto tm = (TableModelSto) jTableNarudzbine.getModel();
        try {
            Kontroler.getInstance().obrisiIzBaze(stoid);
        } catch (Exception ex) {
            Logger.getLogger(JPanelSto.class.getName()).log(Level.SEVERE, null, ex);
        }
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setPrintable(new PrintRacun());
        boolean doPrint = job.printDialog();
        if (doPrint) {
            try {
                job.print();
            } catch (PrinterException e) {

            }
        }

        this.getTopLevelAncestor().setVisible(false);
    }//GEN-LAST:event_jButtonStampajActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodaj;
    private javax.swing.JButton jButtonKraj;
    private javax.swing.JButton jButtonStampaj;
    private javax.swing.JComboBox<String> jComboBoxPica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableNarudzbine;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void pripremiFormu(int brStola) {
        List<Narudzbina> listaNarudzbina = null;
        List<Pice> listaPica = null;
        try {
            listaPica = Kontroler.getInstance().vratiPica();
        } catch (Exception ex) {
            Logger.getLogger(JPanelSto.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            listaNarudzbina = Kontroler.getInstance().vratiNarudzbe(brStola);
        } catch (Exception ex) {
            Logger.getLogger(JPanelSto.class.getName()).log(Level.SEVERE, null, ex);
        }

        jComboBoxPica.setModel(new DefaultComboBoxModel(listaPica.toArray()));
        TableModelSto tm = new TableModelSto(listaNarudzbina);
        jTableNarudzbine.setModel(tm);

    }

    class PrintRacun implements Printable {

        TableModelSto tm = (TableModelSto) jTableNarudzbine.getModel();
        int y = 90;

        @Override
        public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
            if (pageIndex > 0) {
                return NO_SUCH_PAGE;
            }
            int ukupno=0;
            Graphics2D g2d = (Graphics2D) graphics;
            g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());

            graphics.drawString("= = = = = = = = = = = = = = =", 100, y = y + 10);
            graphics.drawString("RESTORAN", 100, y = y + 10);
            graphics.drawString("Zadnji rucak", 100, y = y + 10);
            graphics.drawString("- - - - - - - - - - - - - - -", 100, y = y + 10);

            for (Narudzbina n : tm.getLista()) {
                graphics.drawString(" "+n.getPice().getNazivPica(), 100, y = y + 10);
                graphics.drawString(""+n.getKolicina()+"x"+"   "+n.getPice().getCena(), 100, y = y + 10);
                ukupno+=n.getPice().getCena()*n.getKolicina();
            }
            graphics.drawString("Uk. iznos:   "+ukupno+"", 100, y = y + 20);
            graphics.drawString("======================", 100, y = y + 20);
            return PAGE_EXISTS;

        }
    }
}
